version: '3.4'

networks:
  teste:
    name: teste
  
services:
  sqlserver:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - 11433:1433
    networks:
      - teste
      
  authentication.webapi_auth:
    image: authentication.webapi_auth
    container_name: authentication.webapi_auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=sqlserver;Database=DbAuth;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Jwt:Key=15e0e0beaaac6edb63dc815b5a732481ef2ff6fc7ee412ecbdd43d989f121069"
      - "Jwt:ExpireInMinutes=60"
      - "Logging:LogLevel:SerilogDb=Warning"
      - "Logging:LogLevel:Default=Information"
      - "Logging:LogLevel:MicrosoftAspNetCore=Warning"
      - "Logging:LogLevel:System=Warning"
      - "Swagger:FlowLogin=http://localhost:7028/api/v1/auth/flowlogin"
      - "FilterExceptions=false"

    build:
      context: .
      dockerfile: ./Authentication.WebApi/Dockerfile
    ports:
      - '7028:8080'
    depends_on:
      - sqlserver
    networks:
      - teste
