version: '3.4'

networks:
  backend:
    name: backend
  
services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - c:/dados/volumes/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lucas
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: DbAuth
    networks:
      - 'backend'
    expose:
      - 3306

  authentication.webapi_auth:
    image: authentication.webapi_auth
    container_name: authentication.webapi_auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=server=mysql;port=3306;userid=root;password=root;database=DbAuth;"
      - "Jwt:Key=15e0e0beaaac6edb63dc815b5a732481ef2ff6fc7ee412ecbdd43d989f121069"
      - "Jwt:ExpireInMinutes=60"
      - "Logging:LogLevel:SerilogDb=Warning"
      - "Logging:LogLevel:Default=Information"
      - "Logging:LogLevel:MicrosoftAspNetCore=Warning"
      - "Logging:LogLevel:System=Warning"
      - "Swagger:FlowLogin=http://localhost:7028/api/v1/auth/flowlogin"
      - "FilterExceptions=false"

    build:
      context: .
      dockerfile: ./Authentication.WebApi/Dockerfile
    ports:
      - '7028:8080'
    depends_on:
      - mysql
    networks:
      - backend
